# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5a89256c7767475b0487627cc4596ab8075ded45998c91f63b98a0893987880589b3553e877136f1eb8d6bc582b0d10aef1aa63fd2f91ac99ec4e483c865452

test:
  secret_key_base: a1da7354076abd8264ef535fd402cdacd7fe8a891f7e25998555d1f07f40aada0a30f6b417933978831b60bc7a9831b4bb0e6d4bbc8b0c47dbd5d1f5cdfacb62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
